//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kaibasic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kaibasic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_exit_icon {
            get {
                object obj = ResourceManager.GetObject("Actions-exit-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aplphavert_01 {
            get {
                object obj = ResourceManager.GetObject("aplphavert_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_notdrawing_32 {
            get {
                object obj = ResourceManager.GetObject("cursor_notdrawing_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty_gesture {
            get {
                object obj = ResourceManager.GetObject("empty_gesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection try successful..
        /// </summary>
        internal static string messageConnectionTrySuccessful {
            get {
                return ResourceManager.GetString("messageConnectionTrySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect - waiting setCapapilities event.
        /// </summary>
        internal static string messageConnectionWait {
            get {
                return ResourceManager.GetString("messageConnectionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kai is not responding. Check if the dongle is inserted, KaiSDK is running, Kai is on and connected..
        /// </summary>
        internal static string messageKaiNotResponding {
            get {
                return ResourceManager.GetString("messageKaiNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaiSDK is not running. Run KaiSDK to proceed: use the &quot;Run service&quot; button..
        /// </summary>
        internal static string messageKaiSDKNotRunning {
            get {
                return ResourceManager.GetString("messageKaiSDKNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the sensor off, place your hand in a position where the sensor is parallel to the bottom edge of the screen and switch it on..
        /// </summary>
        internal static string messagePYRStart {
            get {
                return ResourceManager.GetString("messagePYRStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace options were automatically configured..
        /// </summary>
        internal static string messageTraceOptionsConfigured {
            get {
                return ResourceManager.GetString("messageTraceOptionsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for Kai.SDK v1.0.0-beta14).
        /// </summary>
        internal static string parKaiSDKVersion {
            get {
                return ResourceManager.GetString("parKaiSDKVersion", resourceCulture);
            }
        }
    }
}
