//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKai.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class MyKaiStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MyKaiStrings defaultInstance = ((MyKaiStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MyKaiStrings())));
        
        public static MyKaiStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connection successful.")]
        public string msgConnectionSuccessful {
            get {
                return ((string)(this["msgConnectionSuccessful"]));
            }
            set {
                this["msgConnectionSuccessful"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kai is not responding. Check if the dongle is inserted, KaiSDK is running, Kai is" +
            " on and connected.")]
        public string msgKaiNotResponding {
            get {
                return ((string)(this["msgKaiNotResponding"]));
            }
            set {
                this["msgKaiNotResponding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MyKai library message:")]
        public string strKaiMessageboxHeader {
            get {
                return ((string)(this["strKaiMessageboxHeader"]));
            }
            set {
                this["strKaiMessageboxHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trying to connect")]
        public string msgConnectionWait {
            get {
                return ((string)(this["msgConnectionWait"]));
            }
            set {
                this["msgConnectionWait"] = value;
            }
        }
    }
}
