//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKai.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class MyKaiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MyKaiSettings defaultInstance = ((MyKaiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MyKaiSettings())));
        
        public static MyKaiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\workspace")]
        public string kaiDataWorkspaceRelativePath {
            get {
                return ((string)(this["kaiDataWorkspaceRelativePath"]));
            }
            set {
                this["kaiDataWorkspaceRelativePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\datasets")]
        public string kaiDataDatasetRelativePath {
            get {
                return ((string)(this["kaiDataDatasetRelativePath"]));
            }
            set {
                this["kaiDataDatasetRelativePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\patterns")]
        public string kaiDataGesturPatternRelativePath {
            get {
                return ((string)(this["kaiDataGesturPatternRelativePath"]));
            }
            set {
                this["kaiDataGesturPatternRelativePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run")]
        public string kaiManagerKAISDKRegistrySubkey {
            get {
                return ((string)(this["kaiManagerKAISDKRegistrySubkey"]));
            }
            set {
                this["kaiManagerKAISDKRegistrySubkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kai.SDK")]
        public string kaiManagerKAIDSKProccessName {
            get {
                return ((string)(this["kaiManagerKAIDSKProccessName"]));
            }
            set {
                this["kaiManagerKAIDSKProccessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Can not run Kai.SDK. Kibasic did not find the SDK’s registry key or the SDK.exe f" +
            "ile.")]
        public string kaiManagerMsgCanNotRunKaiSDK {
            get {
                return ((string)(this["kaiManagerMsgCanNotRunKaiSDK"]));
            }
            set {
                this["kaiManagerMsgCanNotRunKaiSDK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int kaiGesture2DAllowedAnglePIDivider {
            get {
                return ((int)(this["kaiGesture2DAllowedAnglePIDivider"]));
            }
            set {
                this["kaiGesture2DAllowedAnglePIDivider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int kaiWFDrawingRedrawMargin {
            get {
                return ((int)(this["kaiWFDrawingRedrawMargin"]));
            }
            set {
                this["kaiWFDrawingRedrawMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int kaiWFDrawingStdCursorSize {
            get {
                return ((int)(this["kaiWFDrawingStdCursorSize"]));
            }
            set {
                this["kaiWFDrawingStdCursorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int kaiWFDrawingCrossmarkSize {
            get {
                return ((int)(this["kaiWFDrawingCrossmarkSize"]));
            }
            set {
                this["kaiWFDrawingCrossmarkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int kaiWFDrawingMaxStabilizingMarkRadius {
            get {
                return ((int)(this["kaiWFDrawingMaxStabilizingMarkRadius"]));
            }
            set {
                this["kaiWFDrawingMaxStabilizingMarkRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int kaiWFDrawingStabilizingCursorRedrawInterval {
            get {
                return ((int)(this["kaiWFDrawingStabilizingCursorRedrawInterval"]));
            }
            set {
                this["kaiWFDrawingStabilizingCursorRedrawInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public int kaiWFDrawingMinStabilizingMarkRadius {
            get {
                return ((int)(this["kaiWFDrawingMinStabilizingMarkRadius"]));
            }
            set {
                this["kaiWFDrawingMinStabilizingMarkRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int kaiG2DStateMachineMaxStabilizingCounterValue {
            get {
                return ((int)(this["kaiG2DStateMachineMaxStabilizingCounterValue"]));
            }
            set {
                this["kaiG2DStateMachineMaxStabilizingCounterValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int kaiWFDrawingDefaultMode {
            get {
                return ((int)(this["kaiWFDrawingDefaultMode"]));
            }
            set {
                this["kaiWFDrawingDefaultMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int kaiConnectionTimeoutCounterMax {
            get {
                return ((int)(this["kaiConnectionTimeoutCounterMax"]));
            }
            set {
                this["kaiConnectionTimeoutCounterMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int kaiGesture2DDefaultDecimationFrequency {
            get {
                return ((int)(this["kaiGesture2DDefaultDecimationFrequency"]));
            }
            set {
                this["kaiGesture2DDefaultDecimationFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string kaiSDKAuthProcessName {
            get {
                return ((string)(this["kaiSDKAuthProcessName"]));
            }
            set {
                this["kaiSDKAuthProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qwerty")]
        public string kaiSDKAuthProcessSecret {
            get {
                return ((string)(this["kaiSDKAuthProcessSecret"]));
            }
            set {
                this["kaiSDKAuthProcessSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The KAI SDK is now stpped. Click the \"Run Kai SDK\" button to continue. ")]
        public string kaiSDKWasStopped {
            get {
                return ((string)(this["kaiSDKWasStopped"]));
            }
            set {
                this["kaiSDKWasStopped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int kaiWatchdogTimerInterval {
            get {
                return ((int)(this["kaiWatchdogTimerInterval"]));
            }
            set {
                this["kaiWatchdogTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool kaiGestureLowPassFilterApplyOnEnding {
            get {
                return ((bool)(this["kaiGestureLowPassFilterApplyOnEnding"]));
            }
            set {
                this["kaiGestureLowPassFilterApplyOnEnding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int kaiGestureLowPasFilterNumberOfEndingPoints {
            get {
                return ((int)(this["kaiGestureLowPasFilterNumberOfEndingPoints"]));
            }
            set {
                this["kaiGestureLowPasFilterNumberOfEndingPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float kaiGestureLowPassFilterFactor {
            get {
                return ((float)(this["kaiGestureLowPassFilterFactor"]));
            }
            set {
                this["kaiGestureLowPassFilterFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\workspace\\simple-profiler\\last-instant-profile.csv")]
        public string kaiSimpleProfilerFilePath {
            get {
                return ((string)(this["kaiSimpleProfilerFilePath"]));
            }
            set {
                this["kaiSimpleProfilerFilePath"] = value;
            }
        }
    }
}
